### ISSUE TITLE
Cannot clear out the reading list (8:45)

### ISSUE THREAD

**Issue by JoannaBek** [PTFS-Europe/rebus-list-2#102]
Good morning,

As it is nearly impossible to work on my test reading list (JB Test list) at the moment (it takes forever to load and it takes really long time to perform any action), I thought I will just delete all items and start fresh.

So I used ctrl+F5 to start with, and then started deleting all the items - first getting rid of tags, and then of the actual items. 

It was going fine for a while, up to the point when I started to receive this error message, instead of confirmation that the changes has been saved:
![image](https://cloud.githubusercontent.com/assets/16195154/13739358/a3a43850-e9c2-11e5-9a39-e9363aa5e789.png)

I proceeded with getting rid of the readings (the error message still popping up), and then clicked on 'publish'. The reading list was clear.

I went back to the hierarchy tree, pressed ctrl+F5 again and went back to my reading list. All the readings that I have deleted are back where they were.

I think I will need to delete the whole list, but will leave it for now just in case you need to investigate?

All the best,
Joanna

**Comment by AndrewIsh** [comment]
Hi Joanna

I have deleted your list. I think many of the problems you have been experiencing were due to a bug that I fixed at the end of last week. It meant that material in your list might have contained an invalid material type. Anyway, this bug is now fixed. I'd suggest creating a new list and starting from scratch and see how things go.

I'll close this issue.

Many thanks
Andrew
