### ISSUE TITLE
UI: Browse view not displaying all published lists when unauthenticated

### ISSUE THREAD

**Issue by AndrewIsh** [PTFS-Europe/rebus-list-2#109]
This is a new issue that has come out of https://github.com/PTFS-Europe/rebus-list-2/issues/106#issuecomment-199252315

**Comment by AndrewIsh** [comment]
Hi Andrew,

I tried refreshing the page on Friday, but it didn't seem to fix it. However, the display is okay today, but instead my lists have disappeared from view when I'm not logged in (ie public view). I've logged in and my lists are there and published. I'd planned to delete them and create a better structure so took the opportunity to do that this morning and then see if my new lists were visible, but they still don't seem to appear. I am doing something wrong?

Thanks,
Heather

Public browse view of Sheffield's lists (when not logged in):
![image](https://cloud.githubusercontent.com/assets/9194223/13950741/9633d92e-f024-11e5-9bcb-d28a1dfba850.png)

Admin browse view when logged in:
![image](https://cloud.githubusercontent.com/assets/9194223/13950747/a0457850-f024-11e5-848e-4af68292257b.png)

**Comment by AndrewIsh** [comment]
Hi Heather

I see you've been making some changes since logging this issue. The "Sheffield LRS" branch of the hierarchy seems to be published but, as you say, display is inconsistent between unathenticated and authenticated users. (Particularly notice the different position of "Week 1: Introduction to stuff")

Unauthenticated view:
![image](https://cloud.githubusercontent.com/assets/9194223/13950939/d18da83c-f025-11e5-80d9-5be03206ae8e.png)

Authenticated view:
![image](https://cloud.githubusercontent.com/assets/9194223/13950972/0201cf98-f026-11e5-8f43-ba08cf68f5db.png)

Hierarchy view:
![image](https://cloud.githubusercontent.com/assets/9194223/13950988/19754d3a-f026-11e5-8704-0acbcec6421a.png)

I'm tagging @mrenvoize as he might be able to offer some input.

Many thanks
Andrew

**Comment by SharonCocker** [comment]
Hi Andrew,

Yes since logging this issue I've altered the names of my lists, plus add new to try to make them look a little closer to the type of hierarchy we are already used to.  The problem of not being able to see all published lists in unauthenticated view is still an issue. 

Thanks,
Heather

**Comment by mrenvoize** [comment]
As I suspected, this is all to do with the validity periods that have been set and is by design.

So, the idea behind this is that in some institutions they wanted lists to only be visible from the start date of the module in question.

Logically in rebus:list the following must hold true for a list to appear publically.

The list must be 'published' AND today's date must fall between the 'validity_start_date' and the 'validity_end_date'.

Published and Validity dates can be left empty when creating a list in the hierarchy, which will cause them to inherit the parents values for each of these fields (and this will keep going up the tree until the field is defined).

In your particular case, the top level is published and has 'good' dates, then it's a mixed bag beneath with some lists undefined (and thus inheriting) and other defined with a validity_end_date in the past.. and thus not visible to unauthenticated users.

Hope that helps clarify, 

Martin

**Comment by SharonCocker** [comment]
Hi Martin,

I've now removed the dates from the 'problem' lists and yes they do now display. 

Many thanks,
Heather

**Comment by AndrewIsh** [comment]
As this issue appears to be resolved, I'll close it. Feel free to re-open if it's still a problem.

Many thanks
Andrew
