### ISSUE TITLE
[UI] Navigation between lists and sublists

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#129]
Hi,

When Nick last visited Sheffield, we discussed that it would good if the display when viewing a list  (where there are sublists) could possibly display a selectable index of all the lists?  The navigation is difficult for the user to navigate back to the parent list when viewing a sub-list. (see the screenshot examples below - it's difficult to navigate between SCS101 & SCS102).   Would it be possible to make navigation easier for the user as it is with rebus v1?  Nick mentioned he would take our suggestions back with him for discussion.  I wondered if this was on the list for development?

Many thanks,
Heather 

![image](https://cloud.githubusercontent.com/assets/12249067/16188005/4c393f4c-36cb-11e6-872e-addeaecec1c6.png)

![image](https://cloud.githubusercontent.com/assets/12249067/16188021/653d951a-36cb-11e6-84f6-dfe6fac8583e.png)

**Comment by AndrewIsh** [comment]
Hi Heather

Thanks for the feedback. You've made a good point regarding switching between lists that are at the same level in the hierarchy. I've created an issue at our end and will try and look at this this week.

Many thanks
Andrew

**Comment by hloliver** [comment]
Hi - we've had similar conversations with Nick and would definitely support having a selectable index of lists similar to RL1.  

Most of our users access their reading lists from a link on their Moodle course, this is generally to the parent group for that course http://tavi.rebuslist.com/browse.php?parent=3 rather than to individual lists so that they can easily navigate to all of the lists for different modules. 

At the moment in RL2, if we direct students to a similar parent group ie https://tavi.rebuslist.co.uk/#/list/1593 they're faced with a blank screen and in testing they've missed the drop-down menus so don't know where to start.  We could turn every parent list into a 'how to..' page but it seems a bit cumbersome.

There may be another way around this, but I haven't come across it yet.
best wishes
Helen

**Comment by AndrewIsh** [comment]
Hi all

This has now been implemented and will be rolled out with the next update. I'll close this issue, feel free to re-open if you have any questions.

Many thanks
Andrew
