### ISSUE TITLE
UniofSunderland - Ebooks linking incorrectly

### ISSUE THREAD

**Issue by UniofSunderland** [PTFS-Europe/rebus-list-2#146]
Ebooks on old MMR link directly to the indicated book, ebooks on new MMR have reverted to going to the Dawson's homepage and student is expected to then search and find the item.

Using this example from the LAC278 list

![linking to items from lac278 list](https://cloud.githubusercontent.com/assets/20297411/16582893/cafafebc-42a9-11e6-9b22-76687b43971c.JPG)

Clicking on the shelf icon should show catalogue availability - links to error message from EDS.
http://search.ebscohost.com/login.aspx?direct=true&site=eds-live&scope=site&db=cat00941a^sunder.389842

![linking to a catalogue item](https://cloud.githubusercontent.com/assets/20297411/16582899/d4f9748e-42a9-11e6-83ac-e3c9baa1b0db.JPG)

Clicking on the ebook option should go direct to the specified book
![linking to an ebook item](https://cloud.githubusercontent.com/assets/20297411/16582929/04e38afe-42aa-11e6-82ab-e343fe33919c.JPG)

On our old system it works like this
Clicking on shelf icon
![old mmr clicking on shelf icon](https://cloud.githubusercontent.com/assets/20297411/16582970/4722748e-42aa-11e6-9703-39aaf605f1f5.JPG)
Old MMR clicking on ebook icon
![old mmr clicking on ebook link](https://cloud.githubusercontent.com/assets/20297411/16582976/53340404-42aa-11e6-8437-316335bb9f6c.JPG)

**Comment by AndrewIsh** [comment]
Hi

Thanks for the feedback. We're aware of problems with some links, there is currently work underway to improve this. I'll update this issue once the work is complete and available on your server.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi

Significant work improving this area has occurred since this issue was raised. I've just checked the list in question (https://sunderland.rebuslist.co.uk/#/list/11290) and I can see that the link is still not working as you would expect. Looking at the material in the database, the record we have only contains the link to the EDS page, which is why you're taken there when the "Find item on shelf" button is clicked. I suspect we may need to refresh the data on your RL instance to bring in all links from EDS. I'll tag @mrenvoize in this comment in case he has anything to add.

Many thanks
Andrew

**Comment by fionaborthwick1** [comment]
Hi,

Having checked a few examples in list 11290, I think that this is working as expected now.  You have the Find Items on Shelf button which takes you to your library catalogue and you also have the option to view the full text.

If you find that there are still problems then please log a ticket on the helpdesk providing an example.

Thanks,
Fiona
