### ISSUE TITLE
UniofSunderland - Filters displaying intermittently

### ISSUE THREAD

**Issue by UniofSunderland** [PTFS-Europe/rebus-list-2#147]
Sometimes there are no filter options available on lists - sometimes full options are displayed, sometimes there is only the materials options and sometimes you click on materials options and get a blank screen.  Some examples below
![filter options displaying intermittently](https://cloud.githubusercontent.com/assets/20297411/16583101/32e76ef6-42ab-11e6-888c-6eaf0f8425d7.JPG)
![no filter options](https://cloud.githubusercontent.com/assets/20297411/16583103/373f0c98-42ab-11e6-8729-91503c719a84.JPG)

**Comment by AndrewIsh** [comment]
Hi

Thanks for the information. I'll create an internal issue and investigate.

Many thanks
Andrew

**Comment by janetc** [comment]
York St John have also reported this

**Comment by paulwilliamsBCU** [comment]
Also seeing this at BCU - please see https://bcu.rebuslist.co.uk/#/list/2774 for a list with no filteroptions where there should be.

**Comment by fionaborthwick1** [comment]
I discussed this issue with Sunderland today. This particular problem is a show stopper for them as they make heavy use of tags and therefore the ability to filter by tag is key.  For example they have certain material that students are required to read before they are allowed to attend a lecture so it is essential that the rebus:list gives the easy access to find out what these materials are - e.g. Week 1 tag.

I told them about the new sublist functionality which they may decide to use instead of tags but they need to think about this some more and do require the filter option to work before they can even think about going live.

**Comment by AndrewIsh** [comment]
Improvements have now been made to the material filtering. This will be pushed out in the next update. I'll close this issue, feel free to re-open if it continues to be a problem
