### ISSUE TITLE
No option to change password

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#165]
Hi
I can't see an option for a user to change their password anymore - has this been removed or am I just missing it?
best wishes
Helen

**Comment by mrenvoize** [comment]
We had a bit of a security audit and it was decided that to properly conform to modern security practice that instead of a staff member having the right to change another users password, a password reset email should be sent and the user reset the password themselves. 

You should see the option from the manage users page to 'request new password'. 

That's correct isn't it @andrewish

**Comment by hloliver** [comment]
I wondered if it was something like that, but I haven't been able to find a request new password link, I've just looked on the manage users page but still can't see it!

**Comment by AndrewIsh** [comment]
Hi both

You're not going mad, the lack of a "request new password option" is actually an oversight on my part, apologies! I'll sort it out tomorrow.

Thanks
Andrew

**Comment by mrenvoize** [comment]
Oops @andrewish, I should really test the front end a bit harder after changes, I completely missed that that had fallen between the cracks. 

Thanks for bringing it to our attention @hloliver

**Comment by AndrewIsh** [comment]
The work on this has now been done and will be rolled out in the next update. I'll update this issue when it is available.

**Comment by hloliver** [comment]
Great, thanks Andrew
