### ISSUE TITLE
Material Search 'Whole Words'

### ISSUE THREAD

**Issue by mrenvoize** [PTFS-Europe/rebus-list-2#177]
Currently the material search is an ILIKE carried out over a series of metadata fields.  This ILIKE is not 'word boundary' sensitive and it should be.

**Comment by janetc** [comment]
Hi Martin - Elizabeth made this comment - it may be relevant to this issue?

"What I was getting at was that for a 2 word phrase to work for existing lists and copac you need the inverted commas but when you use that phrase it returns a null result for the Library Catalogue due to the way the connector works.  This is a concept that academics will not cope with very well even if librarians can manage it.  Ideally we need the same searching logic for all sources – i.e. inverted commas for all or none."

**Comment by AndrewIsh** [comment]
Mmmm, she has a point. I reckon we need to get Alex to build a rebus:list connector ASAP, then we can move this sort of logic to the connect end on a per-customer/connector level

**Comment by mrenvoize** [comment]
Broken out these comments into their own issue: #205

**Comment by mrenvoize** [comment]
Please also see our recent [blog post](https://ptfs-europe.github.io/rebus-list/update/2016/08/16/Add_item.html)

**Comment by mrenvoize** [comment]
This is now corrected... We will always search the phrase form of the search string first and append the word form after.
