### ISSUE TITLE
'Add item as' option missing

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#253]
We seem to have lost the 'Add item as' option when selecting an item from the connector results - all we see are select/deselect options

![screenshot 2016-10-14 13 59 45](https://cloud.githubusercontent.com/assets/12201255/19388361/1ff60c7e-9217-11e6-9f77-42353dc38ee7.png)

can this be reinstated so that we can add book chapters, or has it been moved somewhere else?

(I had posted this as an update to 'Adding a book chapter #132' but realised that it was a closed issue so not sure if it would come through to you so have opened this new one - apologies for duplicating posts)

Thanks
Helen

**Comment by hloliver** [comment]
I've just discovered that the option is there if I'm selecting an item from the EBSCO connector, but not from the Koha one, so perhaps it's always been the case - if so is it possible to include this option when selecting items from Koha too?
Thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for this. The "Add item as" option is offered for materials of type "Book" and "Journal", from these it is possible to create materials "Book section" or "Journal article" respectively. Looking at the screenshot you posted, the material in question appears to have not have a material type specified in the search results, therefore an "Add item as" option cannot be offered.

Investigating further, a number of your Koha materials are being returned with either no material type or an unknown material type. I'll speak to @a-sassmannshausen to determine whether this is due to our connector not mapping them correctly, or whether we're not being supplied with them by your z39.50 server.

Many thanks
Andrew

**Comment by mrenvoize** [comment]
@AndrewIsh Did this get followed up upon?  
@janetc do Tavi have a copy of your shiny pre-migration questionnaire yet?

**Comment by AndrewIsh** [comment]
Will chase up with @a-sassmannshausen

**Comment by mrenvoize** [comment]
I'm going to close this one as it relates to getting the connectors right.  In issue #301 I have requested hloliver complete our examples questionnaire so Alex and I may more consistently configure the connector.
