### ISSUE TITLE
Adding Book Sections

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#263]
Hi
I've been using the 'add item as' feature but have found that not all of the data is pulled through or displayed

ie adding book section from EBSCO pulls through all details apart from publisher/publication place so these fields have to be entered manually.
The chapter title is also entered manually but when the record is added to the list this field isn't displayed

Example: https://tavi.rebuslist.co.uk/#/list/2043 
![2016-11-05_1710](https://cloud.githubusercontent.com/assets/12201255/20032091/d9941454-a37a-11e6-8889-706aaf437742.png)

can you take a look
thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Many thanks for this. Interesting, we've not seen this before. It's possible that the last problem you mention, "The chapter title is also entered manually but when the record is added to the list this field isn't displayed" could be down to a problem with the "chapter" material template. Anyway, I'll investigate.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Helen

The missing `publisher` / `publisher-place` may be due to missing connector mappings for those fields, I'll tag @a-sassmannshausen to see if he can give any insight.

The material in question does not have a populated 'title' field. You said:
>The chapter title is also entered manually but when the record is added to the list this field isn't displayed

Do you know which field you added it to? There is this in the Chapter number field: "Comments on transference and countertransference in the initial analytic meeting", if this is intended to be the chapter title, it should be in the Title field.

I hope this helps.

**Comment by hloliver** [comment]
Hi Andrew
I've been adding the chapter title to the ‘Chapter Name/Number’ field, wrongly assuming that you'd labelled the field 'name' rather than 'titlle'! There doesn’t seem to be a chapter title field in any of the sections, the Title section only seems to cater for the book title rather than chapters - have I missed something?
Helen

![add book section - section details](https://cloud.githubusercontent.com/assets/12201255/21006928/f1df746e-bd32-11e6-8a57-532eb953c776.png)

**Comment by mrenvoize** [comment]
Expected in 14th February 2017 bugfix release.

**Comment by mrenvoize** [comment]
This issue was moved to PTFS-Europe/rebus-list#2283

**Comment by AndrewIsh** [comment]
A fix for this has been released - closing
