### ISSUE TITLE
Optionally Display list year with list title

### ISSUE THREAD

**Issue by mrenvoize** [PTFS-Europe/rebus-list-2#276]
We need a system preference along the lines of 'Display course code with list title' but for the 'list year' metafield.

**Comment by fionaborthwick1** [comment]
This was raised at Sunderland yesterday. The year automatically appeared next to the list name in RL1 but it doesn't by default in RL2. It will display if entered manually as part of the list name.  If the year does not display then it can provide quite a lot of confusion for staff who work with the list as there can be multiple entries - especially if lists are kept at rollover.  Obviously the list ID is present but they would like the year to display to make it more obvious so that staff do not edit the wrong list.

They also suggested that perhaps it could be permission controlled - e.g. if your login has a STAFF level access then do not see the old lists?

**Comment by mrenvoize** [comment]
You've merged two enhancements there.. i'll split out the second one into it's own issue: #278

**Comment by mrenvoize** [comment]
As for this issue itself, it's been on the list for months but hasn't been high enough priority to get done yet.  It's not a big job though.

**Comment by mrenvoize** [comment]
Closing duplicate of #41
