### ISSUE TITLE
Find item on Shelf icon missing

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#283]
Hi - records imported into list using the Koha connector have lost the 'Find item on shelf' icon, and the title is no longer hyperlinked to the opac record

ie https://tavi.rebuslist.co.uk/#/list/2089

Can you take a look?
thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Many thanks for this, apologies for the delay in responding. I've had a look at the list and can see the records don't appear to contain the necessary URLs to enable to LMS links to display. This is most likely due to the data in your rebus:list needing refreshing (Therefore, I'm tagging @mrenvoize).

Many thanks
Andrew

**Comment by mrenvoize** [comment]
Closing as a duplicate of other linking related issues #300, #301
