### ISSUE TITLE
Odd linking behaviour

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#300]
Can you take a look at the second item (On the Apprehension of Beauty)  on this list: https://tavi.rebuslist.co.uk/#/list/2338 

The reference was added to the list via our Discovery connector - the title, and Find Item on Shelf icon both link to the full-text on Discovery, but the View Full Text icon links to our Rebus2 home page

https://www.screencast.com/t/I82ECaox 

Thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for reporting this. The "View full text" button is displaying because the item has an ISSN, however in your Global Preferences you do not have a link resolver specified, so the OpenURL link is erroneously being created pointing to your RL2 instance rather than a link resolver. This is a bug, the "View full text" button should not try to create an OpenURL link if there is no link resolver to receive it.

I'll create an issue to address this. I'll try and get a fix sorted today and we can push that on to your instance during our Monday night / Tuesday morning upgrade period.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Helen

Thinking more about this, I think I'll hold back on producing an urgent fix for the bug I mentioned since that's not really the core issue here, the core issue is seemingly the mapping of article URLs in EDS as mentioned in #300 and #301 .

Many thanks
Andrew

**Comment by mrenvoize** [comment]
Expected: Before May 30th Release

**Comment by AndrewIsh** [comment]
Hi Helen

Just to let you know, a fix has just completed for this. It will be rolled out in next Monday's upgrade.

I'll close this issue, if you continue to see problems, feel free to re-open it.

Many thanks
Andrew

**Comment by hloliver** [comment]
Thanks, will check it out on Tuesday

Helen
