### ISSUE TITLE
Hierarchy - lists not re-ordered in user interface

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#54]
Hello

I've just started playing about with the hierarchy, and although I have re-arranged my lists to the preferred order in the admin site this isn't reflected on the user interface, and when I log out and back in again the lists have reverted back to the order in which they were created (most recent are listed first).

The lists come under the TAV hierarchy, I've attached screenshots.

This is likely to be a problem for us if we can't set the preferred order of the lists as the tutors require some of the reading lists to be more prominent than others

Can you take a look?

Thanks 
Helen (Tavistock & Portman Library)

![hierarchy_order_in_admin](https://cloud.githubusercontent.com/assets/12201255/12818959/e91f5e90-cb50-11e5-95b8-bf12229e1297.jpg)
![hierarchy_order_in_ui](https://cloud.githubusercontent.com/assets/12201255/12818958/e918b0e0-cb50-11e5-90b8-79edfde27180.jpg)

**Comment by AndrewIsh** [comment]
Hi Helen

Many thanks for your question.

This is an issue we're aware of and, currently, it is not possible to re-order lists in the way you describe. Although the user interface will allow you to do it, the change is not persistent as you have observed.

It is definitely on the list of issues, however, I am not sure at this stage when it will be addressed. I'll be sure to update this issue as soon as it is resolved.

Many thanks
Andrew

**Comment by hloliver** [comment]
Thanks Andrew, it was my first chance to have a proper look at it so thought I might have missed something!
Hoping to spend more time on it over the next few days
best wishes
Helen

Helen Oliver

Systems Librarian
Tavistock & Portman NHS Foundation Trust
Tavistock Centre
120 Belsize Lane
London NW3 5BA

tel 020 8938 2318
email: holiver@tavi-port.ac.uk

**Comment by AndrewIsh** [comment]
Also raised here https://github.com/PTFS-Europe/rebus-list-2/issues/92

**Comment by JoannaBek** [comment]
Hello,

Just to add to this problem: we receive our lists in a weekly order, with readings for each individual week. The lists are very lengthy for some of the subject (specially politics and history), so we are creating individual lists for every week. 
Example:
![image](https://cloud.githubusercontent.com/assets/16195154/13525645/4b2f506c-e1fa-11e5-8bdf-a8b00a9e2ec9.png)

If we are pressed with time, we will only process the first 6 weeks and create the rest when the pressure for the start of the semester eases.

The current setting will mean for us adding the lists backwards - first the last week and then the earlier ones, to create a correct hierarchy. 

It will not allow us to focus on the first six weeks either, because adding further weeks will appear at the top of the hierarchy

Thanks a lot,
Joanna

**Comment by AndrewIsh** [comment]
Hi Joanna

Thanks for that. We do intend addressing the problem and I'll update the issue when a fix has been implemented. As an aside, it's worth noting that you can specify and start and end date for a list during creation, we added this to RL2 specifically for the scenario you're describing. A list will only be displayed in the system between the start and end dates specified, this will hopefully make navigation of the individual weeks easier for students.

Many thanks
Andrew

**Comment by SharonCocker** [comment]
Hi Andrew,

I wondered if there had been any update regarding being able to re-order the hierarchy of lists?   By chance I tried moving a couple of my child lists and after much fiddling they did actually moving into the order I wanted, ie "HQ Test list - SCS101" was originally beneath "HQ Test list - SCS102" (as I created it first), but it is now in the correct order.  I was unsure if what I had done was a fluke or if something had changed.  I also tried with parent lists higher in the hierarchy, but was unable to re-order these, ie I tried to move "HQ Test list - International Faculty" below "Andy Test List" so that all my lists sat together.   

Thanks,
Heather

**Comment by AndrewIsh** [comment]
Hi Heather

Thanks for the query.

The work to enable this has not yet been done. I suspect that, although it _appeared_ that you had re-ordered them, that change would not be persistent and refreshing the page would reset them back to their original order.

We still intend carrying out the work to enable what you're trying to do, I'll try and get an ETA and let you know.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
Hi Heather

Re-ordering of hierarchy items has now been fully implemented and pushed out. I'll close this issue. Feel free to reopen if you continue to see problems.

Many thanks
Andrew

**Comment by SharonCocker** [comment]
Hi Andrew,

I've tried moving some of my lists, but struggled to do this easily.  Sometimes it did work for me, but I often found it tricky to get the list to stay where I wanted it (it kept jumping back to it's original position) and also sometimes it would become stuck and freeze in not quite the correct position (please see screenshots showing "HQ test list - International Faculty".   However, this is good that re-ordering is going to be possible. 

Many thanks,
Heather 

![image](https://cloud.githubusercontent.com/assets/12249067/16612684/28ad12f0-4360-11e6-8510-c264895e1088.png)

![image](https://cloud.githubusercontent.com/assets/12249067/16612727/5aabbc52-4360-11e6-8037-6a0f1334afc5.png)
