### ISSUE TITLE
Discrepancies between edit mode and preview mode

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#56]
Hello
I've been trying to work out what happens to the preview version of the list when you save a draft, and when you publish the list

I entered a note/tag to an item then saved the draft, then a note/tag to a different item and published it, however it didn't seem to be working consistently (mainly the changes weren't shown in the preview version however I did it), but after saving AND publishing I discovered that I was getting completely different results in edit mode and preview mode - I have highlighted with text boxes in different colours for each record which will hopefully make it a little bit clearer.

https://preview2.rebuslist.com/#/list/59 

I'm on an iMac running OSX Yosemite and have tried in Safari Version 9.0.2 (10601.3.9) and Chrome Version 48.0.2564.103 (64-bit), both with the same results.

Thanks
Helen

![discrepancies_preview](https://cloud.githubusercontent.com/assets/12201255/12889114/5d05d7e0-ce75-11e5-964d-0123713f768d.png)
![discrepancies_edit](https://cloud.githubusercontent.com/assets/12201255/12889115/5d09580c-ce75-11e5-8fb9-5c837438a5e1.png)

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for this. I'm not 100% clear on what problem you're describing. Would it be possible for you to let me have an exact workflow of what causes the problem you're describing please? I need to be able to replicate it so I can investigate further.

Many thanks
Andrew

**Comment by hloliver** [comment]
Hello Andrew
I'm wondering whether this particular list just got a bit tangled up, as I've tested it since on other lists and they've behaved as you would expect.

But, here it is for the record, with apologies as it's a bit long-winded!
1. I created a new list called D24 Unit C (https://preview2.rebuslist.com/#/list/59)
2. Clicked on Edit this List
3. In Essential Readings block clicked on Add New Item
4. Searched for and added several items, and added a note to the first reference
5. here I may have saved the list, then gone back in to edit to publish the list so that I could see the references in the preview mode
   _At this point I wanted to find out what happened when you saved but didn't publish, and what happened if you published without saving_
6. Back in edit I added a note to the second reference (Stirling) and a tag - both of these said 'testing saved drafts'
7. I saved the list to see if these changes were visible in the preview mode
8. I then went back in to list to see what happened when I added a note/tag to the third record (Hoyle) and published the list without saving it - at this point the note and tag disappeared _(when I tried that today the note and tag were saved and appeared on the public site, which definitely didn't happen yesterday)_

I then realised that the preview mode and the edit mode were displaying different notes and tags (see highlighted screenshots sent yesterday)

Today when I tested to see if I could manually add items in Safari (#55) after following your suggestion of purging the local data, I inadvertently chose the same list to add an item to - and although I was able to add an item manually (third one down imaginatively called 'test article') I wasn't then able to delete it, though subsequent tests on other lists in Safari were fine.

If you think that it's just this particular list I can scrap it, and will keep a closer eye next time

best wishes
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks very much for the additional information. I'm concerned about things disappearing when publishing the list.

Here's a quick summary of how edit mode / publishing works.  There can be two versions of your list, the draft version (which we refer to as the buffer) and the published version. When you're in edit mode, you're working on the buffer for that list, visible only to you. When you save your draft, you're saving the buffer in it's current state for later editing. The version that is visible to the wider world (the published version) is unchanged until you publish the buffer. When you do so, the current state of the buffer is transferred to the published version and the buffer is deleted, until you start another editing session, at which point a new buffer is created from the current published version of the list.

It certainly shouldn't be necessary to save the list prior to publishing it. Every change you make while in edit mode is saved in real-time so, in truth, the "Save draft" button is something of a misnomer since the draft is already saved, what you're actually doing is unlocking the draft, so someone else can edit it (as a draft is locked to you while you're working on it).

All that isn't really relevant to your problem, but I thought it might be useful since you seemed interested in what happens when saving and publishing.

I'm not inclined to think that the list in question has got "tangled up", but I'm very interested in how things could be disappearing. It might be worth starting a new list and just seeing if you see similar behaviour, if you do, could you describe exactly what you did, I need to be able to replicate it in order to determine the problem.

Many thanks
Andrew

**Comment by hloliver** [comment]
Hello Andrew
Thanks for the explanation.  I'll create a new list let you know if this occurs again, a couple of colleagues are also going to take a look at the preview site this week so I've asked them to watch out for similar issues.
best wishes
Helen

Helen Oliver

Systems Librarian
Tavistock & Portman NHS Foundation Trust
Tavistock Centre
120 Belsize Lane
London NW3 5BA

tel 020 8938 2318
email: holiver@tavi-port.ac.u

**Comment by AndrewIsh** [comment]
Hi Helen

I'm going to close this issue. If you are still seeing problems, feel free to reopen.

Many thanks
Andrew
