### ISSUE TITLE
Manual entries - fields disappearing, not saving

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#61]
When adding a manual entry, only minimal details are being saved. In the following screenshot, the editors, publisher and URL where all added to the entry, but on clicking finish, only the title and ISBN details are saved. This happened twice for the same item. No error message to say data wasn't being saved. 

List number is: https://uhi.rebuslist.com/#/list/1553 
Firefox v44. 

![manual entry data disappearing](https://cloud.githubusercontent.com/assets/17139950/12943229/c7b54bbc-cfd7-11e5-95ce-066ed58d3e3e.png)

**Comment by richughes** [comment]
Hi. Update on this. When I published the list, the additional metadata appeared, but I think the time lag in the details appearing might be confusing for list editors. I'm not sure where the id number "2-5364" has appeared from either, I think this should be the bibliographic record number from the LMS. 

![manual data update](https://cloud.githubusercontent.com/assets/17139950/12945209/da4f5216-cfe3-11e5-8497-1388879d7c41.png)

**Comment by AndrewIsh** [comment]
Hi Richard

Thanks for the update. I think the delay in metadata appearing is due to a bug that will shortly be addressed. I've checked your database and all the metadata is being correctly populated, it's purely the display side that is problematic. Once the bug is fixed, this problem should go away. I'll close this issue for now.

Many thanks
Andrew
