### ISSUE TITLE
[UI suggestion] Search box layout

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#66]
The search box in Preview is quite small and not obvious to users, or what it is for.   The search box in v.1 is much larger, lower down the page and more obvious of it's function.  Would it be possible to change the search box to a similar design?   (please see screenshot of v.1) 

Thanks,
Heather
![image](https://cloud.githubusercontent.com/assets/12249067/13115303/13fdbbbe-d58f-11e5-848f-b362d04ea4bb.png)

**Comment by AndrewIsh** [comment]
Hi Heather

Thanks for this. The appearance of all aspects of the user interface can be modified by customers themselves via CSS, this is done via the Global Settings page and is covered in the RL2 training.

I hope this answers your question, if not, feel free to re-open this issue.

Many thanks
Andrew

**Comment by mrenvoize** [comment]
Adding to @AndrewIsh response, the new location of the search box was carefully chosen for two pretty good reasons. 
- It's common UI practice to have a search box in the top right, and studies have show it's the second place a user will look after 'top centre' for such a feature.
  - It allows the search box to always be immediately accessible, rather than driving a user to always return home before submitting a second search. This is also a best practice feature.

However, as Andrew has alluded to, should a customer wish to embed a search box up front and centre on their 'home' page, then this will be possible (and I intend on coming up with an example) via the system preferences.
