### ISSUE TITLE
"Journal article" not recognized when adding a new item

### ISSUE THREAD

**Issue by JoannaBek** [PTFS-Europe/rebus-list-2#79]
Good morning,

I am trying to add a few items to my test list. Rebus doesn't seem to be recognizing journal articles, despite this item type being on the list of items:
![image](https://cloud.githubusercontent.com/assets/16195154/13389804/8a1e7676-dec2-11e5-8b51-3d76e7fb73b7.png)

Thanks,
Joanna

**Comment by AndrewIsh** [comment]
Hi Joanna

Thanks for this. This is because the connector that preview2 is using (Bradford ILS) was missing a configuration option to translate the ILS material type for Journal Article to a rebus:list compatible one. I have now added this and note that the material type is now being correctly identified.

I hope this helps.

Regards
Andrew
