### ISSUE TITLE
Error message: server unavailable

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#96]
Hi

After creating a manual entry and trying to save it I got the following error message and it didn't appear to save:
![server not available](https://cloud.githubusercontent.com/assets/17139950/13526831/a10ef692-e202-11e5-8b60-265b67536403.png)

After the error message disappeared, I refreshed the browser and got the following:

![oops error message](https://cloud.githubusercontent.com/assets/17139950/13526890/f96e897e-e202-11e5-8a14-fbd00c8994b8.png)

I tried the "recover" option and it said server unavailable again. The manual entry is now appearing though, despite the error messages. 

I'd been adding items quite steadily this morning, but the system slowed considerably just before midday. 

Many thanks

Richard

**Comment by fionaborthwick1** [comment]
- Just to add to this - this was happening quite often during the
  training session yesterday.  At one stage I advised one of the ladies to
  select discard rather than recover and then close the tab and start again
  as she was getting in a complete loop.

Fiona

On 4 March 2016 at 12:19, richughes notifications@github.com wrote:

> Hi
> 
> After creating a manual entry and trying to save it I got the following
> error message and it didn't appear to save:
> [image: server not available]
> https://cloud.githubusercontent.com/assets/17139950/13526831/a10ef692-e202-11e5-8b60-265b67536403.png
> 
> After the error message disappeared, I refreshed the browser and got the
> following:
> 
> [image: oops error message]
> https://cloud.githubusercontent.com/assets/17139950/13526890/f96e897e-e202-11e5-8a14-fbd00c8994b8.png
> 
> I tried the "recover" option and it said server unavailable again. The
> manual entry is now appearing though, despite the error messages.
> 
> I'd been adding items quite steadily this morning, but the system slowed
> considerably just before midday.
> 
> Many thanks
> 
> Richard
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PTFS-Europe/rebus-list-2/issues/96.

## 

_Fiona Borthwick_

Customer Services Consultant

_T:_ +44 (0) 1483 378728

_F:_ +44 (0) 800 756 6384

_E:_ fiona.borthwick@ptfs-europe.com

www.ptfs-europe.com

 https://www.ptfs-europe.com/

Registered in the United Kingdom No. 06416372   VAT Reg No. 925 7211 30

The information contained in this email message may be privileged,
confidential and protected from disclosure. If you are not the
intended recipient, any dissemination, distribution or copying is
strictly prohibited. If you think that you have received this email
message in error, please email the sender at info@ptfs-europe.com

**Comment by AndrewIsh** [comment]
Hi Richard

I think the brief unavailability of the server was me restarting rebus:list after pushing an update to List:it to your server. Sorry about that.

Thanks for the information Fiona. Strange, I'll investigate.

Many thanks
Andrew

**Comment by AndrewIsh** [comment]
This seems to have been a combination of me restarting rebus:list while Richard was using it and problems with simultaneous editing of the same list during the training. Closing.
